name: Build Snakeibo Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-11-jdk wget
        pip install --upgrade pip
        pip install buildozer cython ffpyplayer kivy kivmob

    - name: Install Android SDK/NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
        mkdir -p $HOME/android-sdk
        unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620"

        echo "export ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export ANDROIDNDK=$HOME/android-sdk/ndk/23.1.7779620" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK/AAB
      run: |
        buildozer android release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Snakeibo-build
        path: bin/*.apk
